### PR TITLE
Fix get<bool> in near.ts

### LINKED ISSUE #12: get <bool> is broken
It assumes bool is a number and tries to parse 'false' and 'true' as a number, which always results in false. We should either either fix parse, or replace `false` and `true` to 0 and 1

### PR DESCRIPTION
**Pull request by evgenykuzyakov**
Fixes #12 
Also refactoring get<T> to support APIs to parse results for async calls that returns basic types. E.g. if you want to do an async call to simple sum, e.g.
```
export function sum(a: i32, b: i32): i32 {
   return a + b;
}
```
it would return you bytes array that contains a string integer, e.g. `42`. To parse it you would use a function:
```
let intResult = near.parseFromBytes<i32>(result.buffer);
```

### CODE REVIEW

**Comment by vgrichina** [comment]
> Also refactoring get to support APIs to parse results for async calls that returns basic types. E.g. if you want to do an async call to simple sum, e.g.

I wouldn't focus much on this, cause IMO we should make bindgen for cross-contract calls instead. I know it's kinda overdue, but I guess it's mostly cause we weren't really building apps using cross-contract.

File: near.ts [hunk 1]
```diff
@@ -1063,6 +1045,65 @@ export let context: Context = new Context();
...
+    }
+    if (isString<T>() || isInteger<T>()) {
+      return parseFromString<T>(bytesToString(bytes), defaultValue);
+    } else {
+      let v = instantiate<T>();
+      return v.decode(bytes);
+    }
+  }
+
+  export function bytesToString(bytes: Uint8Array): string {
```
Comment (vgrichina) [inline near.ts]: Note that assemblyscript kinda plans to solve this in their own way, so maybe we shouldn't export these, see
https://github.com/AssemblyScript/assemblyscript/pull/564
